Add POJO&DAO for Hosts and Categories, and some changes to project
rainbowhuanguw/CS5200 pull request #14
Opened 2023-03-22 23:40 UTC by NekodRider

2023-03-22 23:57 UTC, rainbowhuanguw requested changes

2023-03-22 23:57 UTC, rainbowhuanguw commented on AirEats/java/aireats/model/Hosts.java
> +        super();
this line is unnecessary

2023-03-22 23:57 UTC, rainbowhuanguw commented on AirEats/java/aireats/dal/CategoriesDao.java
> +            StringBuilder categoryListStr = new StringBuilder();
replace line 38 to 43 with 
```String categoryStr = String.join(", ", category.getCategoryList());```

2023-03-22 23:57 UTC, rainbowhuanguw commented on AirEats/java/aireats/dal/CategoriesDao.java
> +            StringBuilder categoryListStr = new StringBuilder();
same here, replace with string join statement

2023-03-22 23:57 UTC, rainbowhuanguw commented on AirEats/java/aireats/model/Categories.java
> +        super();
this line is unnecessary

2023-03-23 00:39 UTC, NekodRider commented
- removed auto-generated `Super()`
- use `String.join()` instead of `StringBuilder` in `Categories`

2023-03-23 04:20 UTC, rainbowhuanguw commented on AirEats/src/main/java/aireats/model/Categories.java
> +package aireats.model;
change class names Categories, Hosts, YelpUsers to singular form

2023-03-23 04:20 UTC, rainbowhuanguw approved these changes

2023-03-23 04:43 UTC, merged